name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy to Oracle Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via git and rebuild
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/shiny
            git fetch --tags
            git checkout ${{ github.ref_name }}
            docker compose build web
            docker compose up -d web
